### PR TITLE
index.html revamp

### PR DESCRIPTION
**Pull request by Furitenman**
The old site is full of spaghetti code and it barely sticks together. This is a much cleaner look for the website. It also adds bootstrap, which would allow anyone to add/edit/delete stuff without breaking the website completely. Below you can see pictures of how it looks like.

Site dark theme
Site light theme

### CODE REVIEW

**Comment by riichinomics** [comment]
Can't you just use bootstrap from the CDN and not add 20000 line of unnecessary source code?

**Comment by riichinomics** [comment]
Also why do you have both the minified and unminified javascript files commited?

**Comment by Furitenman** [comment]
@riichinomics I can do that no problem.

**Comment by watterle** [comment]
I personally like the current horizontal "where to play" section more, but the rest is great. Do you plan to update the other pages too?

**Comment by watterle** [comment]
Perfect. Fix that section and I'll merge. Thanks for your help.

**Comment by Furitenman** [comment]
Here's the finished "where to play" section. I also added all the new changes. I have to fix the theme switcher in all the other pages, but I'd rather put that on another pull request.

Let me know what you think
Screen 21 04 2021

**Comment by watterle** [comment]
uhhh I fucked up something

**Comment by watterle** [comment]
there was some conflict but I pressed on like a retard, just open another

**Comment by watterle** [comment]
fuck I shouldn't do this while drunk

**Pull request merged**
